export default [
    { id: 1, name: "Maçã Gala",unid:'kg', img: "img/maca-gala.jpg", price: 2.99 },
    { id: 2, name: "Banana Nanica",unid:'kg', img: "img/banana-nanica.jpg", price: 1.99 },
    { id: 3, name: "Laranja Pera",unid:'kg', img: "img/laranja-pera.jpg", price: 3.49 },
    { id: 4, name: "Morango",unid:'kg', img: "img/morango.jpg", price: 5.99 },
    { id: 5, name: "Uva Thompson",unid:'kg', img: "img/uva-thompson.jpg", price: 4.99 },
    { id: 6, name: "Abacaxi",unid:'kg', img: "img/abacaxi.jpg", price: 6.99 },
    { id: 7, name: "Melancia",unid:'kg', img: "img/melancia.jpg", price: 8.99 },
    { id: 8, name: "Melão",unid:'kg', img: "img/melao.jpg", price: 7.49 },
    { id: 9, name: "Manga",unid:'kg', img: "img/manga.jpg", price: 4.49 },
    { id: 10, name: "Kiwi",unid:'kg', img: "img/kiwi.jpg", price: 6.49 },
    { id: 11, name: "Limão",unid:'kg', img: "img/limao.jpg", price: 2.49 },
    { id: 12, name: "Pêssego",unid:'kg', img: "img/pessego.jpg", price: 5.49 },
    { id: 13, name: "Ameixa",unid:'kg', img: "img/ameixa.jpg", price: 4.79 },
    { id: 14, name: "Pera",unid:'kg', img: "img/pera.jpg", price: 3.99 },
    { id: 15, name: "Cereja",unid:'kg', img: "img/cereja.jpg", price: 9.99 },
    { id: 16, name: "Framboesa",unid:'kg', img: "img/framboesa.jpg", price: 8.49 },
    { id: 17, name: "Amora",unid:'kg', img: "img/amora.jpg", price: 7.99 },
    { id: 18, name: "Mirtilo",unid:'kg', img: "img/mirtilo.jpg", price: 8.99 },
    { id: 19, name: "Goiaba",unid:'kg', img: "img/goiaba.jpg", price: 3.79 },
    { id: 20, name: "Maracujá",unid:'kg', img: "img/maracuja.jpg", price: 6.79 },
    { id: 21, name: "Abacate",unid:'kg', img: "img/abacate.jpg", price: 5.79 },
    { id: 22, name: "Coco",unid:'kg', img: "img/coco.jpg", price: 7.79 },
    { id: 23, name: "Mamão",unid:'kg', img: "img/mamao.jpg", price: 6.29 },
    { id: 24, name: "Romã",unid:'kg', img: "img/roma.jpg", price: 8.29 },
    { id: 25, name: "Figo",unid:'kg', img: "img/figo.jpg", price: 7.29 },
    { id: 26, name: "Tangerina",unid:'kg', img: "img/tangerina.jpg", price: 3.29 },
    { id: 27, name: "Acerola",unid:'kg', img: "img/acerola.jpg", price: 6.99 },
    { id: 28, name: "Carambola",unid:'kg', img: "img/carambola.jpg", price: 7.49 },
    { id: 29, name: "Pitaya",unid:'kg', img: "img/pitaya.jpg", price: 9.49 },
    { id: 30, name: "Caju",unid:'kg', img: "img/caju.jpg", price: 5.99 },
    { id: 31, name: "Jaca",unid:'kg', img: "img/jaca.jpg", price: 8.99 },
    { id: 32, name: "Graviola",unid:'kg', img: "img/graviola.jpg", price: 9.99 },
    { id: 33, name: "Sapoti",unid:'kg', img: "img/sapoti.jpg", price: 6.49 },
    { id: 34, name: "Nectarina",unid:'kg', img: "img/nectarina.jpg", price: 5.49 },
    { id: 35, name: "Caqui",unid:'kg', img: "img/caqui.jpg", price: 6.99 },
    { id: 36, name: "Pinhão",unid:'kg', img: "img/pinhao.jpg", price: 7.99 },
    { id: 37, name: "Castanha do Pará", unid:'kg',    img: "img/castanha-do-para.jpg",    price: 12.99  },
    { id: 38, name: "Noz",unid:'kg', img: "img/noz.jpg", price: 11.99 },
    { id: 39, name: "Amêndoa",unid:'kg', img: "img/amendoa.jpg", price: 10.99 },
    { id: 40, name: "Avelã",unid:'kg', img: "img/avela.jpg", price: 12.49 },
    { id: 41, name: "Pistache",unid:'kg', img: "img/pistache.jpg", price: 13.49 },
    { id: 42, name: "Cenoura",unid:'kg', img: "img/cenoura.jpg", price: 2.99 },
    { id: 43, name: "Batata",unid:'kg', img: "img/batata.jpg", price: 2.49 },
    { id: 44, name: "Cebola",unid:'kg', img: "img/cebola.jpg", price: 1.99 },
    { id: 45, name: "Alho",unid:'kg', img: "img/alho.jpg", price: 3.49 },
    { id: 46, name: "Tomate",unid:'kg', img: "img/tomate.jpg", price: 3.99 },
    { id: 47, name: "Alface",unid:'kg', img: "img/alface.jpg", price: 2.79 },
    { id: 48, name: "Rúcula",unid:'kg', img: "img/rucula.jpg", price: 3.29 },
    { id: 49, name: "Espinafre",unid:'kg', img: "img/espinafre.jpg", price: 4.29 },
    { id: 50, name: "Brócolis",unid:'kg', img: "img/brocolis.jpg", price: 5.29 },
    { id: 51, name: "Couve-flor",unid:'kg', img: "img/couve-flor.jpg", price: 4.99 },
    { id: 52, name: "Repolho",unid:'kg', img: "img/repolho.jpg", price: 3.79 },
    { id: 53, name: "Couve",unid:'kg', img: "img/couve.jpg", price: 3.79 },
    { id: 54, name: "Pepino",unid:'kg', img: "img/pepino.jpg", price: 2.29 },
    { id: 55, name: "Abobrinha",unid:'kg', img: "img/abobrinha.jpg", price: 3.49 },
    { id: 56, name: "Pimentão",unid:'kg', img: "img/pimentao.jpg", price: 4.49 },
    { id: 57, name: "Quiabo",unid:'kg', img: "img/quiabo.jpg", price: 5.49 },
    { id: 58, name: "Chuchu",unid:'kg', img: "img/chuchu.jpg", price: 2.99 },
    { id: 59, name: "Vagem",unid:'kg', img: "img/vagem.jpg", price: 4.79 },
    { id: 60, name: "Ervilha",unid:'kg', img: "img/ervilha.jpg", price: 6.29 },
    { id: 61, name: "Milho",unid:'kg', img: "img/milho.jpg", price: 3.99 },
    { id: 62, name: "Beterraba",unid:'kg', img: "img/beterraba.jpg", price: 3.79 },
    { id: 63, name: "Nabo",unid:'kg', img: "img/nabo.jpg", price: 2.79 },
    { id: 64, name: "Rabanete",unid:'kg', img: "img/rabanete.jpg", price: 3.29 },
    { id: 65, name: "Acelga",unid:'kg', img: "img/acelga.jpg", price: 4.29 },
    { id: 66, name: "Agrião",unid:'kg', img: "img/agriao.jpg", price: 5.29 },
    { id: 67, name: "Almeirão",unid:'kg', img: "img/almeirao.jpg", price: 4.99 },
    { id: 68, name: "Mostarda",unid:'kg', img: "img/mostarda.jpg", price: 3.79 },
    { id: 69, name: "Salsão",unid:'kg', img: "img/salsao.jpg", price: 4.29 },
    { id: 70, name: "Aspargo",unid:'kg', img: "img/aspargo.jpg", price: 8.29 },
    { id: 71, name: "Alcachofra",unid:'kg', img: "img/alcachofra.jpg", price: 9.29 },
    { id: 72, name: "Inhame",unid:'kg', img: "img/inhame.jpg", price: 5.79 },
    { id: 73, name: "Mandioca",unid:'kg', img: "img/mandioca.jpg", price: 4.79 },
    { id: 74, name: "Batata Doce",unid:'kg', img: "img/batata-doce.jpg", price: 3.79 },
    { id: 75, name: "Gengibre",unid:'kg', img: "img/gengibre.jpg", price: 7.29 },
    { id: 76, name: "Açafrão",unid:'kg', img: "img/acafrao.jpg", price: 8.29 },
    { id: 77, name: "Coentro",unid:'kg', img: "img/coentro.jpg", price: 3.29 },
    { id: 78, name: "Salsa",unid:'kg', img: "img/salsa.jpg", price: 3.29 },
    { id: 79, name: "Cebolinha",unid:'kg', img: "img/cebolinha.jpg", price: 2.99 },
    { id: 80, name: "Manjericão",unid:'kg', img: "img/manjericao.jpg", price: 4.49 },
    { id: 81, name: "Alecrim",unid:'kg', img: "img/alecrim.jpg", price: 5.49 },
    { id: 82, name: "Louro",unid:'kg', img: "img/louro.jpg", price: 6.49 },
    { id: 83, name: "Orégano",unid:'kg', img: "img/oregano.jpg", price: 5.99 },
    { id: 84, name: "Tomilho",unid:'kg', img: "img/tomilho.jpg", price: 6.99 },
    { id: 85, name: "Hortelã",unid:'kg', img: "img/hortela.jpg", price: 4.99 },
    { id: 86, name: "Sálvia",unid:'kg', img: "img/salvia.jpg", price: 5.49 },
    { id: 87, name: "Endro",unid:'kg', img: "img/endro.jpg", price: 6.49 },
    { id: 88, name: "Estragão",unid:'kg', img: "img/estragao.jpg", price: 7.49 },
    { id: 89, name: "Pimenta",unid:'kg', img: "img/pimenta.jpg", price: 3.99 },
    { id: 90, name: "Pimenta do Reino", unid:'unid',  img: "img/pimenta-do-reino.jpg",  price: 4.99 },
    { id: 91, name: "Cominho",unid:'kg', img: "img/cominho.jpg", price: 5.99 },
    { id: 92, name: "Canela",unid:'kg', img: "img/canela.jpg", price: 6.99 },
    { id: 93, name: "Cravo",unid:'kg', img: "img/cravo.jpg", price: 7.99 },
    { id: 94, name: "Noz Moscada",unid:'kg', img: "img/noz-moscada.jpg", price: 8.99 },
    { id: 95, name: "Cardamomo",unid:'kg', img: "img/cardamomo.jpg", price: 9.99 },
    { id: 96, name: "Anis Estrelado", unid:'UND',    img: "img/anis-estrelado.jpg",    price: 10.99  },
    { id: 97, name: "Gergelim",unid:'kg', img: "img/gergelim.jpg", price: 6.49 },
    { id: 98, name: "Linhaça",unid:'kg', img: "img/linhaca.jpg", price: 5.49 },
    { id: 99, name: "Chia",unid:'kg', img: "img/chia.jpg", price: 7.49 },
    { id: 100, name: "Quinoa",unid:'kg', img: "img/quinoa.jpg", price: 8.49 },
    { id: 101, name: "Aveia",unid:'kg', img: "img/aveia.jpg", price: 4.99 },
    { id: 102, name: "Arroz Integral", unid:'kg',    img: "img/arroz-integral.jpg",    price: 5.99  },
    { id: 103, name: "Feijão",unid:'kg', img: "img/feijao.jpg", price: 3.99 },
    { id: 104, name: "Lentilha",unid:'kg', img: "img/lentilha.jpg", price: 4.99 },
    { id: 105, name: "Grão de Bico",unid:'kg', img: "img/grao-de-bico.jpg", price: 6.99 },
    { id: 106, name: "Ervilha Seca",unid:'kg', img: "img/ervilha-seca.jpg", price: 5.99 },
    { id: 107, name: "Soja",unid:'kg', img: "img/soja.jpg", price: 4.49 },
    { id: 108, name: "Trigo",unid:'kg', img: "img/trigo.jpg", price: 3.49 },
    { id: 109, name: "Cevada",unid:'kg', img: "img/cevada.jpg", price: 5.49 },
    { id: 110, name: "Centeno",unid:'kg', img: "img/centeno.jpg", price: 6.49 },
    { id: 111, name: "Milho de Pipoca", unid:'pct',    img: "img/milho-de-pipoca.jpg",    price: 4.79  },
    { id: 112, name: "Amendoim",unid:'kg', img: "img/amendoim.jpg", price: 6.29 },
    { id: 113, name: "Castanha de Caju",unid:'kg',   img: "img/castanha-de-caju.jpg",    price: 11.99  },
    { id: 114, name: "Azeitona",unid:'kg', img: "img/azeitona.jpg", price: 7.79 },
    { id: 115, name: "Picles",unid:'kg', img: "img/picles.jpg", price: 6.79 },
    { id: 116, name: "Palmito",unid:'kg', img: "img/palmito.jpg", price: 9.79 },
    { id: 117, name: "Cogumelo",unid:'kg', img: "img/cogumelo.jpg", price: 8.79 },
    { id: 118, name: "Alcaparra",unid:'kg', img: "img/alcaparra.jpg", price: 7.99 },
    { id: 119, name: "Tomate Seco",unid:'kg', img: "img/tomate-seco.jpg", price: 8.49 },
    { id: 120, name: "Azeite de Oliva",unid:'kg',    img: "img/azeite-de-oliva.jpg",    price: 14.99  },
    { id: 121, name: "Vinagre",unid:'kg', img: "img/vinagre.jpg", price: 4.49 },
    { id: 122, name: "Mostarda (Condimento)",unid:'kg',    img: "img/mostarda-condimento.jpg",    price: 5.49  },
    { id: 123, name: "Ketchup",unid:'kg', img: "img/ketchup.jpg", price: 3.99 },
    { id: 124, name: "Maionese",unid:'kg', img: "img/maionese.jpg", price: 4.99 },
    { id: 125, name: "Molho de Soja",unid:'kg', img: "img/molho-de-soja.jpg", price: 6.99 },
    { id: 126, name: "Mel",unid:'kg', img: "img/mel.jpg", price: 9.99 },
    { id: 127, name: "Geleia",unid:'kg', img: "img/geleia.jpg", price: 7.49 },
    { id: 128, name: "Doce de Leite",unid:'kg', img: "img/doce-de-leite.jpg", price: 8.49 },
    { id: 129, name: "Manteiga",unid:'kg', img: "img/manteiga.jpg", price: 6.29 },
    { id: 130, name: "Queijo Minas",unid:'kg', img: "img/queijo-minas.jpg", price: 12.99 },
    { id: 131, name: "Queijo Mussarela",unid:'kg',    img: "img/queijo-mussarela.jpg",    price: 13.99  },
    { id: 132, name: "Queijo Parmesão",unid:'kg',    img: "img/queijo-parmesao.jpg",    price: 15.99  },
    { id: 133, name: "Queijo Gouda",unid:'kg', img: "img/queijo-gouda.jpg", price: 14.49 },
    { id: 134, name: "Queijo Provolone",unid:'kg',    img: "img/queijo-provolone.jpg",    price: 13.49  },
    { id: 135, name: "Iogurte Natural",unid:'kg',    img: "img/iogurte-natural.jpg",    price: 5.79  },
    { id: 136, name: "Leite",unid:'kg', img: "img/leite.jpg", price: 3.79 },
    { id: 137, name: "Ovos",unid:'kg', img: "img/ovos.jpg", price: 6.99 },
    { id: 138, name: "Pão Integral",unid:'kg', img: "img/pao-integral.jpg", price: 7.99 },
    { id: 139, name: "Pão de Forma",unid:'kg', img: "img/pao-de-forma.jpg", price: 6.49 },
    { id: 140, name: "Biscoito Integral",unid:'kg',    img: "img/biscoito-integral.jpg",    price: 8.99  },
    { id: 141, name: "Barra de Cereal",unid:'kg',    img: "img/barra-de-cereal.jpg",    price: 4.29  },
    { id: 142, name: "Suco de Laranja",unid:'kg',    img: "img/suco-de-laranja.jpg",    price: 6.99  },
    { id: 143, name: "Suco de Maçã",unid:'kg', img: "img/suco-de-maca.jpg", price: 5.99 },
    { id: 144, name: "Água de Coco",unid:'kg', img: "img/agua-de-coco.jpg", price: 7.49 },
    { id: 145, name: "Chá Verde",unid:'kg', img: "img/cha-verde.jpg", price: 8.49 },
    { id: 146, name: "Café",unid:'kg', img: "img/cafe.jpg", price: 10.99 },
    { id: 147, name: "Cacau em Pó",unid:'kg', img: "img/cacau-em-po.jpg", price: 9.49 },
    { id: 148, name: "Chocolate Amargo",unid:'un',    img: "img/chocolate-amargo.jpg",    price: 11.49  },
    { id: 149, name: "Chocolate ao Leite",unid:'un',    img: "img/chocolate-ao-leite.jpg",    price: 10.49  },
    { id: 150, name: "Farinha de Trigo Integral",unid:'kg',    img: "img/farinha-de-trigo-integral.jpg",    price: 6.79  },
  ];
  