export default [
    { id: 1, name: "Maçã Gala",unid:'kg', img: "./img/maca-gala.webp", price: 2.99 },
    { id: 2, name: "Banana Nanica",unid:'kg', img: "./img/banana-nanica.webp", price: 1.99 },
    { id: 3, name: "Laranja Pera",unid:'kg', img: "./img/laranja-pera.webp", price: 3.49 },
    { id: 4, name: "Morango",unid:'kg', img: "./img/morango.webp", price: 5.99 },
    { id: 5, name: "Uva Thompson",unid:'kg', img: "./img/uva-thompson.webp", price: 4.99 },
    { id: 6, name: "Abacaxi",unid:'kg', img: "./img/abacaxi.webp", price: 6.99 },
    { id: 7, name: "Melancia",unid:'kg', img: "./img/melancia.webp", price: 8.99 },
    { id: 8, name: "Melão",unid:'kg', img: "./img/melao.webp", price: 7.49 },
    { id: 9, name: "Manga",unid:'kg', img: "./img/manga.webp", price: 4.49 },
    { id: 10, name: "Kiwi",unid:'kg', img: "./img/kiwi.webp", price: 6.49 },
    { id: 11, name: "Limão",unid:'kg', img: "./img/limao.webp", price: 2.49 },
    { id: 12, name: "Pêssego",unid:'kg', img: "./img/pessego.webp", price: 5.49 },
    { id: 13, name: "Ameixa",unid:'kg', img: "./img/ameixa.webp", price: 4.79 },
    { id: 14, name: "Pera",unid:'kg', img: "./img/pera.png", price: 3.99 },
    { id: 15, name: "Castanha do Pará", unid:'kg',    img: "./img/castanha-do-para.webp",    price: 12.99  },
    { id: 16, name: "Goiaba",unid:'kg', img: "./img/goiaba.webp", price: 3.79 },
    { id: 17, name: "Maracujá",unid:'kg', img: "./img/maracuja.webp", price: 6.79 },
    { id: 18, name: "Abacate",unid:'kg', img: "./img/abacate.webp", price: 5.79 },
    { id: 19, name: "Coco",unid:'kg', img: "./img/coco.webp", price: 7.79 },
    { id: 20, name: "Mamão",unid:'kg', img: "./img/mamao.webp", price: 6.29 },
    { id: 21, name: "Romã",unid:'kg', img: "./img/roma.webp", price: 8.29 },
    { id: 22, name: "Figo",unid:'kg', img: "./img/figo.webp", price: 7.29 },
    { id: 23, name: "Tangerina",unid:'kg', img: "./img/tangerina.webp", price: 3.29 },
    { id: 24, name: "Acerola",unid:'kg', img: "./img/acerola.webp", price: 6.99 },
    { id: 25, name: "Carambola",unid:'kg', img: "./img/carambola.webp", price: 7.49 },
    { id: 26, name: "Pitaya",unid:'kg', img: "./img/pitaya.webp", price: 9.49 },
    { id: 27, name: "Caju",unid:'kg', img: "./img/caju.webp", price: 5.99 },
    { id: 28, name: "Jaca",unid:'kg', img: "./img/jaca.webp", price: 8.99 },
    { id: 29, name: "Graviola",unid:'kg', img: "./img/graviola.webp", price: 9.99 },
    { id: 30, name: "Caqui",unid:'kg', img: "./img/caqui.webp", price: 6.99 },
    

  ];
  